---
version: "3"

services:
  os01:
    image: opensearchproject/opensearch:2.1.0
    container_name: os01
    # hostname: os01
    domainname: example.local
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./opensearch-01.yml:/usr/share/opensearch/config/opensearch.yml
      - ./log4j.properties:/usr/share/opensearch/config/log4j2.properties:ro
      - ./config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
      - ./certs:/usr/share/opensearch/config/certificates:ro
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch
  os02:
    image: opensearchproject/opensearch:2.1.0
    container_name: os02
    domainname: example.local
    # hostname: os02
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ./opensearch-02.yml:/usr/share/opensearch/config/opensearch.yml
      - ./log4j.properties:/usr/share/opensearch/config/log4j2.properties:ro
      - ./config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
      - ./certs:/usr/share/opensearch/config/certificates:ro
    networks:
      - opensearch
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.1.0
    container_name: dashboards
    hostname: dashboards
    domainname: example.local
    ports:
      - 5601:5601
    expose:
      - "5601"
    volumes:
      - ./certs:/usr/share/opensearch-dashboards/config/certificates:ro
      - ./opensearch-dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    environment:
      OPENSEARCH_HOSTS: '["https://os01:9200"]'
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    networks:
      - opensearch

networks:
  opensearch:

volumes:
  opensearch-data1:
  opensearch-data2:
